AllCops:
  TargetRubyVersion: 3.3

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Layout/SpaceAroundOperators:
  EnforcedStyleForExponentOperator: space
